In [11]:
# Import dependices
import pandas as pd
import csv

In [12]:
# Import CSV file and create df
file = "test_data.csv"
shotlist_df = pd.read_csv(file)
shotlist_df.head()

,Game_Date,Loc_X,Loc_Y,Player_ID,Player_Name,Team_ID,Team_Name
0,20001101,28,7,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
1,20001102,0,0,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
2,20001102,-189,78,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
3,20001102,0,0,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
4,20001102,0,0,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets

In [13]:
shotlist_df.dtypes

Game_Date       int64
Loc_X           int64
Loc_Y           int64
Player_ID       int64
Player_Name    object
Team_ID         int64
Team_Name      object
dtype: object

In [14]:
# Want to drop all rows with no shot data (ie. where Loc_X and Loc_Y are '0')

# createa new dataframe object with the Loc_X and Loc_Y as '0'
removeRows = shotlist_df[(shotlist_df['Loc_X'] == 0) & (shotlist_df['Loc_Y'] == 0)].index
removeRows

Int64Index([   1,    3,    4,    6,    9,   10,   14,   15,   16,   19,
            ...
             941,  959,  961, 1084, 1085, 1089, 1094, 1095, 1096, 1098],
           dtype='int64', length=376)

In [15]:
# Drop this object from our Shotlist_df
shotlist_df.drop(removeRows, inplace=True)

In [16]:
shotlist_df.head()

,Game_Date,Loc_X,Loc_Y,Player_ID,Player_Name,Team_ID,Team_Name
0,20001101,28,7,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
2,20001102,-189,78,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
5,20001102,32,89,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
7,20001104,-155,26,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
8,20001104,-128,120,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets

In [17]:
## We need to either convert Game_Date to reflect our seasons in the format 2001-02
## or create some code that will loop through Game_Data and give us a list with seasons in format 2001-02

In [18]:
## create identical df to test on
shotlist2_df = shotlist_df
shotlist2_df.head()

,Game_Date,Loc_X,Loc_Y,Player_ID,Player_Name,Team_ID,Team_Name
0,20001101,28,7,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
2,20001102,-189,78,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
5,20001102,32,89,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
7,20001104,-155,26,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets
8,20001104,-128,120,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets

In [19]:
## Using 'Game_Date' column and '&' logic  to create a new 'Season' column

shotlist2_df.loc[(shotlist2_df.Game_Date >= 20001030) & (shotlist2_df.Game_Date < 20010430), 'Season'] = '2000-01'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20011030) & (shotlist2_df.Game_Date < 20020430), 'Season'] = '2001-02'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20020418) & (shotlist2_df.Game_Date < 20030430), 'Season'] = '2002-03'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20030418) & (shotlist2_df.Game_Date < 20040430), 'Season'] = '2003-04'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20040418) & (shotlist2_df.Game_Date < 20050430), 'Season'] = '2004-05'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20050418) & (shotlist2_df.Game_Date < 20060430), 'Season'] = '2005-06'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20060418) & (shotlist2_df.Game_Date < 20070430), 'Season'] = '2006-07'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20070418) & (shotlist2_df.Game_Date < 20080430), 'Season'] = '2007-08'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20080418) & (shotlist2_df.Game_Date < 20090430), 'Season'] = '2008-09'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20090418) & (shotlist2_df.Game_Date < 20100430), 'Season'] = '2009-10'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20100418) & (shotlist2_df.Game_Date < 20110430), 'Season'] = '2010-11'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20110418) & (shotlist2_df.Game_Date < 20120430), 'Season'] = '2011-12'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20120418) & (shotlist2_df.Game_Date < 20130430), 'Season'] = '2012-13'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20130418) & (shotlist2_df.Game_Date < 20140430), 'Season'] = '2013-14'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20140418) & (shotlist2_df.Game_Date < 20150430), 'Season'] = '2014-15'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20150418) & (shotlist2_df.Game_Date < 20080430), 'Season'] = '2015-16'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20160418) & (shotlist2_df.Game_Date < 20080430), 'Season'] = '2016-17'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20170418) & (shotlist2_df.Game_Date < 20080430), 'Season'] = '2017-18'
shotlist2_df.loc[(shotlist2_df.Game_Date >= 20180418) & (shotlist2_df.Game_Date < 20080430), 'Season'] = '2018-19'

In [20]:
shotlist2_df

,Game_Date,Loc_X,Loc_Y,Player_ID,Player_Name,Team_ID,Team_Name,Season
0,20001101,28,7,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
2,20001102,-189,78,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
5,20001102,32,89,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
7,20001104,-155,26,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
8,20001104,-128,120,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
11,20001108,-176,116,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
12,20001109,100,196,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
13,20001109,70,241,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
17,20001114,237,51,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
18,20001114,159,181,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
20,20001116,174,13,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
21,20001116,-200,74,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
22,20001116,174,13,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
23,20001120,47,30,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
24,20001120,18,19,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
25,20001120,-23,4,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
26,20001120,18,15,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
27,20001122,-94,4,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
28,20001122,-155,137,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
29,20001124,167,108,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
31,20001130,-67,66,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
33,20001130,-183,76,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
34,20001130,148,82,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
35,20001202,-109,36,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
38,20010117,237,19,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
40,20010127,157,152,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
41,20010216,-103,26,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
42,20010221,-138,87,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2000-01
46,20011030,-94,-13,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2001-02
47,20011101,-206,150,1505,Tariq Abdul-Wahad,1610612743,Denver Nuggets,2001-02
...,...,...,...,...,...,...,...,...
1335,20150102,0,1,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1336,20150102,0,26,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1337,20150104,7,9,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1338,20150104,-16,9,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1339,20150104,-68,175,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1340,20150104,-2,159,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1341,20150104,-8,167,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1342,20150105,31,37,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1343,20150105,-82,67,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1344,20150105,-4,-2,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1345,20150107,24,4,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1346,20150107,4,4,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1347,20150107,0,7,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1348,20150107,-7,-8,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1349,20150107,-4,12,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1350,20150109,-19,6,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1351,20150109,-79,41,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1352,20150109,15,112,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1353,20150109,-30,156,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1354,20150109,-2,7,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1355,20150109,17,142,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1356,20150111,70,137,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1357,20150111,65,129,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1358,20150111,-76,172,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1359,20150111,-24,15,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1360,20150111,15,20,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1361,20150111,4,20,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1362,20150113,51,165,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1363,20150115,0,151,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15
1364,20150115,75,159,2430,Carlos Boozer,1610612747,Los Angeles Lakers,2014-15